# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-11 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='ac_patron_repeticion_semanal',
            field=models.CharField(blank=True, default=b'', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_fdesp',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 12, 11, 10, 13, 12, 43488), null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_empieza',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 10, 13, 12, 44832)),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_termina_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 11, 10, 13, 12, 44872)),
        ),
    ]
