# Generated by Django 2.1.7 on 2019-03-26 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190206_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='ac_OpcionSerie',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_despd',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_enf',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_estado',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.EstadoActividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_fdesp',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 26, 14, 32, 8, 205822), null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_instrucciones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_nunca',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_patron_repeticion_semanal',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ac_repetirComo',
            field=models.CharField(blank=True, choices=[('LM', 'Lunes, Miercoles y Viernes'), ('MJ', 'Martes y Jueves'), ('LV', 'Lunes a Viernes'), ('DI', 'Diario'), ('SM', 'Semanal')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='amistad',
            name='a_estado',
            field=models.CharField(choices=[('A', 'Aprobada'), ('R', 'Rechazada'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='c_pais',
            field=models.ForeignKey(default='Venezuela', on_delete=django.db.models.deletion.CASCADE, to='web.Pais'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='d_imagen',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='d_imagen_negra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estadoactividad',
            name='ea_estado',
            field=models.CharField(choices=[('Planifico', 'Planifico'), ('Abierta Reversible', 'Abierta Reversible'), ('Abierta Irreversible', 'Abierta Irreversible'), ('Activa', 'Activa'), ('Culminada', 'Culminada'), ('Cancelada', 'Cancelada'), ('En Conflicto', 'En Conflicto')], default='Planifico', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadoactividad',
            name='ea_imagen',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_calle',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_correo',
            field=models.EmailField(blank=True, default='victrois@gmail.com', max_length=70),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_direccion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_edificioCasa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_iniciales',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_moneda',
            field=models.CharField(choices=[('$  ', '$'), ('Bs.', 'Bs.'), ('€  ', '€')], default='Bs.', max_length=3),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_planVictorius',
            field=models.ForeignKey(default='Core', on_delete=django.db.models.deletion.CASCADE, to='web.PlanVictorius'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_razon_social',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_redSocial_Facebook',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_redSocial_Instagram',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_redSocial_Twitter',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_telefono1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_telefono2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_tipoCuenta',
            field=models.CharField(choices=[('N', 'Natural'), ('J', 'Juridica')], default='J', max_length=1),
        ),
        migrations.AlterField(
            model_name='marca',
            name='m_urbanizacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='marca_notificacion',
            name='mn_estado',
            field=models.CharField(choices=[('C', 'Creada'), ('A', 'Aceptada'), ('R', 'Rechazada'), ('V', '')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pago',
            name='p_codigoInterno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='p_medio',
            field=models.IntegerField(choices=[(0, 'TRANSFERENCIA'), (1, 'DEPOSITO'), (2, 'POS'), (3, 'VPOS'), (4, 'CHEQUE'), (5, 'EFECTIVO'), (6, 'POR_COBRAR'), (7, 'BECA')], default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='p_status',
            field=models.IntegerField(choices=[(0, 'Por Conciliar'), (1, 'Conciliado'), (2, 'No Conciliado'), (3, 'Pendiente de Pago')], default=0),
        ),
        migrations.AlterField(
            model_name='pais',
            name='p_alias',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='planes',
            name='p_nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_moneda',
            field=models.CharField(choices=[('$  ', '$'), ('Bs.', 'Bs.'), ('€  ', '€')], default='Bs.', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_tipo',
            field=models.IntegerField(choices=[(0, 'POR CREDITOS'), (1, 'MENSUAL ILIMITADO'), (2, 'MENSUAL LIMITADO'), (3, 'REFERENCIADO')], default=0),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.FileField(upload_to='profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_apellido',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_aspiraciones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_centros_frecuentados',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_correo',
            field=models.EmailField(blank=True, default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_descripcion_negocio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_nombre',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_nombre_negocio',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_tipo',
            field=models.CharField(blank=True, choices=[('M', 'Marca'), ('A', 'Atleta')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='pr_ubicacion_negocio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='r_estado',
            field=models.CharField(choices=[('A', 'Aprobada'), ('R', 'Rechazada'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_empieza',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 14, 32, 8, 206988)),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_termina',
            field=models.CharField(choices=[('D', 'Terminar en la fecha'), ('R', 'Despues de')], max_length=1),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_termina_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 26, 14, 32, 8, 207021)),
        ),
        migrations.AlterField(
            model_name='serie',
            name='s_tipo',
            field=models.CharField(choices=[('LM', 'Lunes, Miercoles y Viernes'), ('MJ', 'Martes y Jueves'), ('LV', 'Lunes a Viernes'), ('DI', 'Diario'), ('SM', 'Semanal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='tiponotificacion',
            name='tn_tipo',
            field=models.CharField(choices=[('IA', 'Invitacion Afiliacion'), ('SA', 'Solicitud Afiliacion'), ('CA', 'Cancelacion Actividad'), ('RL', 'Reservado desde Lista de espera'), ('MI', 'Marca Informa a Atleta'), ('AI', 'Atleta Informa a Marca'), ('AA', 'Atleta Informa a Atleta'), ('RP', 'Registro de Plan'), ('VP', 'Vencimiento de Plan'), ('RR', 'Registro de Reservación'), ('BM', 'Broadcast Marca')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='tl_accion',
            field=models.CharField(choices=[('RA', 'Reserva de Actividad'), ('CR', 'Cancelacion de Reserva'), ('EE', 'Entrada en Lista de Espera'), ('SE', 'Salida de Lista de Espera'), ('PE', 'Promocion desde Lista de Espera'), ('SA', 'Suspension de Actividad'), ('CP', 'Compra de Plan'), ('RS', 'Reintegro Por Suspension'), ('RX', 'Reintegro Por No Participacion'), ('IP', 'Inactivacion de Plan')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_calle',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_direccion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_edificioCasa',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_entrenador_profile',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_genero',
            field=models.CharField(choices=[('0', 'Sin Indicar'), ('1', 'Masculino'), ('2', 'Femenino')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_iniciales',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_objetivos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='u_urbanizacion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='usuario_notificacion',
            name='un_estado',
            field=models.CharField(choices=[('C', 'Creada'), ('A', 'Aceptada'), ('R', 'Rechazada'), ('V', '')], max_length=2),
        ),
    ]
