from django.conf.urls import include, url
from .views import viewsGeneral,viewsDashBoards, viewsActividades, viewsScripts

app_name = 'web'

urlpatterns = [
    url(r'^$', viewsGeneral.login, name='login'),
    url(r'^requerirLogon$', viewsGeneral.requerirLogon, name='requerirLogon'),
    url(r'^reenviarcorreo/$', viewsGeneral.reenviarcorreo, name='reenviarcorreo'),
    url(r'^token/updateajax$', viewsGeneral.updateajax),
    url(r'^token/p-(?P<pk>[\w\-]+)$', viewsGeneral.activacionporcorreo, name='activate'),
    url(r'^token/(?P<pk>[\w\-]+)$', viewsGeneral.token, name='token'),
    url(r'^registro-marca$', viewsGeneral.registromarca),
    url(r'^(?P<pka>[\w\-]+)/registro-marca$', viewsGeneral.registromarca, name='registromarca'),
    url(r'^centros$', viewsGeneral.centros, name='centros'),
    url(r'^(?P<pka>[\w\-]+)/crearactualizarcuenta$', viewsGeneral.crearactualizarcuentaajax,
        name='creaactualizacuenta'),
    url(r'^(?P<pka>[\w\-]+)/crearactualizarsala$', viewsGeneral.crearactualizarsalaajax, name='crearactualizarsala'),
    url(r'^(?P<pka>[\w\-]+)/actualizarConfigMarca$', viewsGeneral.actualizarConfigMarca, name='actualizarConfigMarca'),
    url(r'^(?P<pka>[\w\-]+)/actualizarConfigAtleta$', viewsGeneral.actualizarConfigAtleta,
        name='actualizarConfigAtleta'),
    url(r'^acerca_de$', viewsGeneral.acerca_de, name='acerca_de'),
    url(r'^cambiarcontrasena$', viewsGeneral.cambiarcontraajax),
    url(r'^clase-cancelarreserva/(?P<pk>[\w\-]+)$', viewsGeneral.clasecancelarajax),
    url(r'^crearactividad$', viewsActividades.crearActividadAjax),
    url(r'^validarsalon$', viewsGeneral.validarsalonajax),
    url(r'^cuentasajax-(?P<pk>[\w\-]+)$', viewsGeneral.cuentasajax),
    url(r'^editarplan$', viewsGeneral.editarplanajax),
    url(r'^forgot$', viewsGeneral.forgotajax, name='forgot'),
    url(r'^habilitarplan$', viewsGeneral.habilitarplanajax),
    url(r'^getplan$', viewsGeneral.getplanajax),
    url(r'^getplanPendientePorCobrar$', viewsGeneral.getPlanPendientePorCobrarAjax),
    url(r'^instructores$', viewsGeneral.instructores, name='instructores'),
    url(r'^login$', viewsGeneral.login, name='login'),
    #url(r'^logout$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^logout$', viewsGeneral.user_logout, name='logout'),
    url(r'^marcarasistencia$', viewsGeneral.marcarasistenciaajax),
    url(r'^mostrarpago$', viewsGeneral.mostrarpagoajax),
    url(r'^mostrarPagoPendientePorCobrar$', viewsGeneral.mostrarPagoPendientePorCobrarAjax),
    url(r'^obteneractividad$', viewsActividades.obtenerActividadAjax),
    url(r'^tabRecarga$', viewsActividades.tabRecarga,name='tabRecarga'),
    url(r'^tabPlanesCentros$', viewsActividades.tabPlanesCentros, name='tabPlanesCentros'),
    url(r'^obteneractividadrecarga$', viewsActividades.obtenerActividadRecargaAjax),
    url(r'^eliminarActividad$', viewsActividades.eliminarActividadAjax),
    url(r'^suspenderActividad$', viewsActividades.suspenderActividadAjax),
    url(r'^reactivarActividad$', viewsActividades.reactivarActividadAjax),
    url(r'^obtenerserie$', viewsGeneral.obtenerserieajax),
    url(r'^procesarpago$', viewsGeneral.pagoajax),
    url(r'^procesarpagoPorCobrar$', viewsGeneral.pagoPorCobrarAjax),
    url(r'^cambiarstatuspago$', viewsGeneral.cambiarStatusPago),
    url(r'^registrarusuario$', viewsGeneral.registrarusuarioajax),
    url(r'^agregarUsuarioExistente$', viewsGeneral.agregarUsuarioExistenteAjax),
    url(r'^solicitudusuario$', viewsGeneral.solicitudusuarioajax),
    url(r'^(?P<pk>[\w\-]+)/atletas$', viewsGeneral.atletascentro),
    url(r'^cambiarmarca/(?P<pk>[\w\-]+)$', viewsGeneral.cambiarmarca),
    url(r'^(?P<pka>[\w\-]+)/confmarca$', viewsGeneral.confmarca, name='confmarca'),
    url(r'^(?P<pka>[\w\-]+)/confatleta$', viewsGeneral.confatleta, name='confatleta'),
    url(r'^(?P<pk>[\w\-]+)/instructores$', viewsGeneral.atletasentrenadores, ),
    url(r'^(?P<pk>[\w\-]+)/calendar$', viewsGeneral.calendarioajax, name='calendarioajax'),
    url(r'^(?P<pk>[\w\-]+)/cancelarreserva$', viewsGeneral.cancelarajax),
    url(r'^(?P<pk>[\w\-]+)/clase-(?P<pka>[\w\-]+)$', viewsActividades.clasedetail),
    url(r'^(?P<pk>[\w\-]+)/comprarplan$', viewsGeneral.comprarajax),
    url(r'^(?P<pk>[\w\-]+)/comprarplan2$', viewsGeneral.comprar2ajax),
    url(r'^(?P<pk>[\w\-]+)/consumos$', viewsGeneral.consumos),
    url(r'^(?P<pk>[\w\-]+)/cuporeservado$', viewsGeneral.cuporeservandoajax),
    url(r'^(?P<pk>[\w\-]+)/dashboard$', viewsDashBoards.dashboard, name='dashboard'),
    url(r'^(?P<pk>[\w\-]+)/dashtableVigentes$', viewsDashBoards.dashtableVigentes, name='dashtableVigentes'),
    url(r'^(?P<pk>[\w\-]+)/dashtableRecientes$', viewsDashBoards.dashtableRecientes, name='dashtableRecientes'),
    url(r'^(?P<pk>[\w\-]+)/estadoentrenador$', viewsGeneral.estadoentrenadorajax),
    url(r'^(?P<pk>[\w\-]+)/perfil-planes-atleta-(?P<pka>[\w\-]+)$', viewsGeneral.perfilPlanesAtleta),
    url(r'^(?P<pk>[\w\-]+)/perfil-atleta-marca-(?P<pka>[\w\-]+)$', viewsGeneral.perfilAtletaMarca),
    url(r'^(?P<pk>[\w\-]+)/perfil-afiliaciones-atleta-(?P<pka>[\w\-]+)$', viewsGeneral.perfilAfiliacionesAtleta),
    url(r'^(?P<pk>[\w\-]+)/perfil-remuneraciones-instructor-(?P<pka>[\w\-]+)$', viewsGeneral.perfilRemuneracionesInstructor),
    url(r'^(?P<pk>[\w\-]+)/perfil-atleta-(?P<pka>[\w\-]+)$', viewsGeneral.perfilatleta),
    url(r'^(?P<pk>[\w\-]+)/perfil-instructor-(?P<pka>[\w\-]+)$', viewsGeneral.perfilatleta),
    url(r'^(?P<pk>[\w\-]+)/consumo-plan-(?P<pka>[\w\-]+)$', viewsGeneral.consumoplan),
    url(r'^(?P<pk>[\w\-]+)/(?P<pka>[\w\-]+)-calendario$', viewsGeneral.calendario),
    url(r'^(?P<pk>[\w\-]+)/(?P<pka>[\w\-]+)-planes$', viewsGeneral.planesatleta),
    url(r'^(?P<pk>[\w\-]+)/reservado$', viewsGeneral.reservandoajax),
    url(r'^(?P<pk>[\w\-]+)/reservadocupo$', viewsGeneral.reservandoajax),
    url(r'^(?P<pk>[\w\-]+)/reservar$', viewsGeneral.reservarajax),
    url(r'^(?P<pkb>[\w\-]+)/h-(?P<pk>[\w\-]+)-(?P<id>[\w\-]+)$', viewsGeneral.historial),
    url(r'^(?P<pk>[\w\-]+)/(?P<pka>[\w\-]+)-pagos$', viewsGeneral.pagospendientes),
    url(r'^ajax/validate_username/$', viewsGeneral.validate_username, name='validate_username'),
    url(r'^ajax/validate_useralias/$', viewsGeneral.validate_useralias, name='validate_useralias'),
    url(r'^ajax/validate_marcaalias/$', viewsGeneral.validate_marcaalias, name='validate_marcaalias'),
    url(r'^ajax/validate_refpago/$', viewsGeneral.validate_refpago, name='validate_refpago'),
    url(r'^ajax/validate_salon/$', viewsActividades.validate_salon, name='validate_salon'),
    url(r'^ajax/getReciboPagoInfo/$', viewsGeneral.getReciboPagoInfo, name='getReciboPagoInfo'),
    url(r'^ajax/enviar_correo_intencion_compra/$', viewsGeneral.enviarCorreoIntencionCompra, name='enviarCorreoIntencionCompra'),
    url(r'^correoBienvenida$', viewsGeneral.correoBienvenida, name='correoBienvenida'),
    url(r'^eliminarUsuario$', viewsGeneral.eliminarUsuario),
    url(r'^crearUsuariosBatch$', viewsScripts.crearUsuariosBatch),
    url(r'^crearUsuariosBatch$', viewsScripts.crearUsuariosBatch),
    url(r'^dashboard$', viewsDashBoards.dashboard,name='dashboard'),
    url(r'^table_body_remuneraciones_instructor$', viewsGeneral.table_body_remuneraciones_instructor, name='table_body_remuneraciones_instructor'),
    url(r'^register$', viewsGeneral.register),
    url(r'^(?P<pk>[\w\-]+)/$', viewsGeneral.perfilmarca, name='perfilmarca'),
    url(r'^(?P<pk>[\w\-]+)/notificaciones$', viewsGeneral.notificacionesAjax, name='notificaciones'),
    url(r'^ajax/aceptarRechazarSolicitud/$', viewsGeneral.aceptarRechazarSolicitudAjax,
        name='aceptarRechazarSolicitudAjax'),

    url(r'^(?P<pka>[\w\-]+)/configuracion_general$', viewsGeneral.configuracionGeneral),
    url(r'^(?P<pk>[\w\-]+)/planes$', viewsGeneral.planes),
    url(r'^(?P<pk>[\w\-]+)/salas$', viewsGeneral.salas),
    url(r'^(?P<pk>[\w\-]+)/cuentas$', viewsGeneral.cuentas),
    url(r'^(?P<pka>[\w\-]+)/gestionar_planes$', viewsGeneral.gestionarPlanes),
    url(r'^(?P<pka>[\w\-]+)/gestionar_salas$', viewsGeneral.gestionarSalas),
    url(r'^(?P<pka>[\w\-]+)/gestionar_cuentas$', viewsGeneral.gestionarCuentas),

    url(r'^(?P<pk>[\w\-]+)/edo-cuenta$', viewsGeneral.estadodecuenta),
    url(r'^table_body_estado_cuenta$', viewsGeneral.table_body_estado_cuenta, name='table_body_estado_cuenta'),

    url(r'^activarDesactivarCuenta$', viewsGeneral.activarDesactivarCuentaAjax),

    url(r'^table_body_planes_atleta$', viewsGeneral.table_body_planes_atleta, name='table_body_planes_atleta'),
    url(r'^(?P<pk>[\w\-]+)/subirAvatar$', viewsGeneral.subirAvatar),

    url(r'^(?P<pk>[\w\-]+)/calendario-atleta$', viewsDashBoards.calendarioAtleta, name='calendario-atleta'),
    url(r'^pagineo_calendario_atleta$', viewsDashBoards.calendarioAtleta, name='pagineo_calendario_atleta'),

    url(r'^(?P<pk>[\w\-]+)/calendario-marca$', viewsDashBoards.calendarioMarca, name='calendario-marca'),
    url(r'^pagineo_calendario_marca$', viewsDashBoards.calendarioMarca, name='pagineo_calendario_marca'),

    url(r'^(?P<pk>[\w\-]+)/perfil-actividades-atleta-(?P<pka>[\w\-]+)$', viewsGeneral.perfilActividadesAtleta),
    url(r'^(?P<pk>[\w\-]+)/pagineo_perfil_actividades_atleta$', viewsGeneral.perfilActividadesAtleta, name='pagineo_perfil_actividades_atleta'),
    url(r'^(?P<pk>[\w\-]+)/carrusel-mis-actividades$', viewsGeneral.carruselMisActividades,name='carrusel-mis-actividades'),

    url(r'^(?P<pk>[\w\-]+)/perfil-actividades-instructor-(?P<pka>[\w\-]+)$', viewsGeneral.perfilActividadesInstructor),
    url(r'^(?P<pk>[\w\-]+)/pagineo_perfil_actividades_instructor$', viewsGeneral.perfilActividadesInstructor, name='pagineo_perfil_actividades_instructor'),

    url(r'^(?P<pk>[\w\-]+)/(?P<pkb>[\w\-]+)-instructor-(?P<pka>[\w\-]+)$', viewsGeneral.instructordetail),

    url(r'perfil-actividades-marca$', viewsGeneral.perfilActividadesMarca, name='perfil-actividades-marca'),
    url(r'perfil-actividades-marca-por-atleta$', viewsGeneral.perfilActividadesMarcaPorAtleta,name='perfil-actividades-marca-por-atleta'),

    url(r'perfil-actividades-atleta$', viewsGeneral.perfilActividadesAtletaPerfil, name='perfil-actividades-atleta'),
    url(r'^(?P<pk>[\w\-]+)/pagineo_perfil_actividades_atleta_perfil$', viewsGeneral.perfilActividadesAtletaPerfil, name='pagineo_perfil_actividades_atleta_perfil'),

    url(r'perfil-planes-atleta$', viewsGeneral.perfilPlanesAtletaPerfil, name='perfil-planes-atleta'),

    url(r'perfil-actividades-instructor$', viewsGeneral.perfilActividadesInstructorPerfil, name='perfil-actividades-instructor'),
    url(r'^(?P<pk>[\w\-]+)/pagineo_perfil_actividades_instructor_perfil$', viewsGeneral.perfilActividadesInstructorPerfil, name='pagineo_perfil_actividades_instructor_perfil'),

    url(r'perfil-remuneraciones-instructor$', viewsGeneral.perfilRemuneracionesInstructorPerfil, name='perfil-remuneraciones-instructor'),

    url(r'^contactos$', viewsGeneral.contactos, name='contactos'),
]